# Generated by Django 4.0.4 on 2022-04-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiacs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZodiacName',
            new_name='Sign',
        ),
    ]
