# Generated by Django 4.0.4 on 2022-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiacs', '0002_rename_zodiacname_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
