# Generated by Django 4.0.4 on 2022-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiacs', '0003_sign_end_date_sign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
